##
# Shorthand for the default node image.
##
default_node_image: &default_node_image
    docker:
      - image: circleci/node:8.10.0
    
    working_directory: ~/repo

version: 2
jobs:
  ################################
  # Dependencies
  ################################

  dependencies:
    <<: *default_node_image

    steps:
      - checkout

      # Restore cached dependencies.
      - restore_cache:
          keys:
          - node-dependencies-{{ checksum "package.json" }}

      # Install dependencies.
      - run:
          name: Gathering Tiberium
          command: yarn install

      # Save to cache.
      - save_cache:
          key: node-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

  ################################
  # Linting
  ################################

  lint:
    <<: *default_node_image

    steps:
      - checkout

      # Restore cached dependencies.
      - restore_cache:
          keys:
          - node-dependencies-{{ checksum "package.json" }}

      # Linting.
      - run:
          name: Stop! It's linter time
          command: yarn lint

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - dependencies:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - dependencies
          filters:
            tags:
              only: /.*/
